version: '3.8'

services:

  devops_db:
    image: postgres
    container_name: devops_db
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5440:5432"

  web:
    container_name: devops_api
    build: . # Build the image from the Dockerfile in the current directory
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - devops_db

  
